openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "8080"
paths:
  /addLecturer:
    post:
      operationId: postAddlecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LECTURER'
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
  /getAllLecturers:
    get:
      operationId: getGetalllecturers
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LECTURER'
  /getLecturer/{staff_number}:
    get:
      operationId: getGetlecturerStaffNumber
      parameters:
      - name: staff_number
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /updateLecturer:
    put:
      operationId: putUpdatelecturer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LECTURER'
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
  /deleteLecturer/{staff_number}:
    delete:
      operationId: deleteDeletelecturerStaffNumber
      parameters:
      - name: staff_number
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    LECTURER:
      required:
      - course_id
      - office_id
      - staff_name
      - staff_number
      - title
      type: object
      properties:
        staff_number:
          type: string
        staff_name:
          type: string
        title:
          type: string
          enum:
          - Mrs
          - Mr
          - Dr
          - Professor
        course_id:
          type: string
        office_id:
          type: integer
          format: int64
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
